### ISSUE TITLE
Fix Graph on load in UI

### ISSUE THREAD

**Issue by spookieoli** [spookieoli/VreeDB#14]
When loaded, the UI graph is to small

**Comment by RamBITS-AI** [comment]
Hi @spookieoli,

Hope this is the issue you are mentioning:

<img width="953" alt="image" src="https://github.com/spookieoli/VreeDB/assets/61575596/dcb33b4d-6ae3-4433-bcc9-00def035fad9">

**Comment by spookieoli** [comment]
Correct, this is the Bug - should we make it more responsive?

**Comment by RamBITS-AI** [comment]
I extracted out the function inside setInterval and invoked it first and then invoked it again in setInterval. This seems to sort of make it more responsive. I also have made reload of gohtml files at run-time possible in DEV mode. Do you think this is desirable for devs and have made the default mode as DEV (for now).

Have a look at the [draft PR](https://github.com/spookieoli/VreeDB/pull/15).
