### ISSUE TITLE
Add Neuralnetbuilder to UI

### ISSUE THREAD

**Issue by spookieoli** [spookieoli/VreeDB#8]

**Comment by RamBITS-AI** [comment]
Hi @spookieoli,

Please share any specifications you would like me to have a look at and any specific UI design that you have in mind for this one. Please also share any tips that would help me along the way.

**Comment by spookieoli** [comment]
Hi @RamBITS-AI, 
ok - no problem. Do we want to use some other platform to talk / plan something like discord?
